language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.14"
  - "7.10"
  - "8.11"
  - "9.11"
  - "10.5"
jobs:
    exclude:
      - node-js: 0.8
        arch: ppc64le
      - node-js: 0.10
        arch: ppc64le
      - node-js: 0.12
        arch: ppc64le
      - node-js: 1.8
        arch: ppc64le
      - node-js: 2.5
        arch: ppc64le
      - node-js: 3.3
        arch: ppc64le
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Setup npm
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm install -g npm@1.2.8000"
  - "npm config set shrinkwrap false"
  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 6 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
  - "test   -z $(npm -ps ls istanbul) || npm run-script test-travis"
  - "test   -z $(npm -ps ls eslint  ) || npm run-script lint"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
